version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: posting_app_postgres
    restart: always
    environment:
      POSTGRES_USER: poster
      POSTGRES_PASSWORD: winterCamp
      POSTGRES_DB: poster_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


